### ISSUE TITLE
HELP major exception crash

### ISSUE THREAD

**Issue by Ferynix** [ZQiu233/QTRHacker#1]
I used the english version (unstable) ;-; so theres no stable english version and i used it once, it worked, i messed around with some of the hacks and it crashed my game. Now every time i try to tap the cross to attach to terraria it pulls the error below, yes i tried reinstalling, redownloading, etc etc restart pc, disable antivirus.
Error:
\************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at QTRHacker.Functions.GameContext..ctor(Int32 pid)
   at QTRHacker.MainForm.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
***********

**Comment by Qiu233** [comment]
Windows 7 or above(x64), .Net 4.5 or above, VC runtime(VC redist) are needed.

**Comment by Qiu233** [comment]
I've drafted a new RELEASE today.
It's much newer than the last one.
Please download this one: 2.4.6895.34851
 @skylerspark
